version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: evolution_db
    restart: always
    environment:
      POSTGRES_DB: evolution
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password123
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
    networks:
      - evolution_network

  evolution-api:
    image: atendai/evolution-api:latest
    container_name: evolution_api
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    env_file:
      - .env.docker
    dns:
      - 8.8.8.8
      - 1.1.1.1  
    volumes:
      - ./data/evolution_instances:/evolution/instances
    networks:
      - evolution_network
    extra_hosts:
      - "host.docker.internal:host-gateway"

  minio:
    image: minio/minio:latest
    container_name: minio_storage
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - ./data/minio:/data
    environment:
      MINIO_ROOT_USER: "admin"
      MINIO_ROOT_PASSWORD: "sua_senha_forte_123"
    command: server /data --console-address ":9001"
    restart: always
    networks:
      evolution_network:
        aliases:
          - s3.meusistema.local

  minio-setup:
    image: minio/mc:latest
    depends_on:
      - minio
    networks:
      - evolution_network
    entrypoint: >
      /bin/sh -c "
      sleep 10;
      /usr/bin/mc alias set myminio http://minio_storage:9000 admin sua_senha_forte_123;
      /usr/bin/mc mb myminio/ads || true;
      /usr/bin/mc anonymous set download myminio/ads;
      exit 0;
      "
networks:
  evolution_network:
    driver: bridge

volumes:
  n8n_data:
  minio_data: