server {
    listen 80;
    server_name sama.app.br;
    return 301 https://$host$request_uri;
}

server {
    listen 443 ssl;
    server_name sama.app.br;

    ssl_certificate /etc/letsencrypt/live/sama.app.br/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/sama.app.br/privkey.pem;

    root /var/www/public;
    index index.php index.html;

    location / {
        try_files $uri $uri/ /index.php?$query_string;
    }

    # AJUSTE FASTCGI (PERFORMANCE)
    location ~ \.php$ {
        fastcgi_split_path_info ^(.+\.php)(/.+)$;
        fastcgi_pass app:9000;
        fastcgi_index index.php;
        include fastcgi_params;
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
        fastcgi_param PATH_INFO $fastcgi_path_info;

        # Timeouts para grandes volumes de dados
        fastcgi_read_timeout 300;
        fastcgi_connect_timeout 300;
        fastcgi_send_timeout 300;
        fastcgi_buffers 16 16k;
        fastcgi_buffer_size 32k;
    }
}

server {
    listen 9000 ssl;
    server_name sama.app.br;
    ssl_certificate /etc/letsencrypt/live/sama.app.br/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/sama.app.br/privkey.pem;
    location / {
        proxy_pass http://minio:9000;
        proxy_set_header Host $host;
    }
}

server {
    listen 8080 ssl;
    server_name sama.app.br;
    ssl_certificate /etc/letsencrypt/live/sama.app.br/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/sama.app.br/privkey.pem;
    location / {
        proxy_pass http://evolution-api:8080;
        proxy_set_header Host $host;
    }
}

server {
    listen 8081;
    server_name sama.app.br;
    location / {
        proxy_pass http://evolution-api:8080;
        proxy_set_header Host $host;
    }
}

